name: C Data Structures CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  memcheck-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential valgrind

    - name: Build and Run Tests with Valgrind
      run: |
        mkdir -p logs
        make unittest SEED=1234 memcheck=true modular=true
        echo "MEMORY CHECK LOGS:"
        cat logs/memcheck.ansi
        echo "TEST DEBUG LOGS:"
        cat logs/debug.ansi
        echo "TEST RESULTS LOGS:"
        cat logs/results.ansi

  benchmark-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential valgrind

    - name: Build and Run Tests with Benchmarks
      run: |
        mkdir -p logs
        make unittest SEED=1234 memcheck=false modular=false
        echo "BENCHMARK LOGS:"
        cat logs/benchmark.csv
        echo "TEST DEBUG LOGS:"
        cat logs/debug.ansi
        echo "TEST RESULTS LOGS:"
        cat logs/results.ansi